### ISSUE TITLE
Route parameter schema format is ignored

### ISSUE THREAD

**Issue by DotnDev** [OpenClassrooms/APITester#19]
If a route has a parameter format defined, for example:

```
      parameters:
        - name: id
          in: path
          description: 'ID'
          required: true
          schema:
            format: uuid
            type: string
            nullable: false
            example: 1ecbbf47-4089-6c16-9612-83a435fde67f
```

The route will throw a 400 Bad Request if the uuid format is incorrect.

The APITester ignores this and inserts `-9999` as a test parameter to test a 404 response, which means the test fails.

<img width="689" alt="Capture d’écran 2022-04-14 à 16 04 28" src="https://user-images.githubusercontent.com/57391746/163407552-2d1408c8-5de3-4682-a7b2-27e04d8fa724.png">
